import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PageFooter from "./footer";
import NavBar from "./navbar";
import NextTopLoader from "nextjs-toploader";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "KiosBedul.id - Website Top-Up #1 Tangerang",
  description: "Generated by turugames",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="id">
      <body className="text-white max-w-full h-full">
        <main className={`${inter.className} bg-[#121a23]`}>
          <NextTopLoader color="#b04e4e" showSpinner={false} height={5} />
          <NavBar />
          <Providers>{children}</Providers>
          <PageFooter />
        </main>
      </body>
    </html>
  );
}
